FROM node:12-alpine

RUN apk update
RUN apk add bash

ENV PORT 3000

EXPOSE 3000
WORKDIR /app

COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock

RUN yarn install

COPY ./dist /app/dist

CMD ["node", "./dist/main.js"]
